# version: "3.8"  # Убираем устаревший параметр

services:
  # Существующие сервисы из твоего docker-compose
  # Убираем сервис server, так как он должен быть в отдельном проекте
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: assist_backend_api_test
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./app:/app/app/
  #     - ./alembic:/app/alembic
  #   depends_on:
  #     - db
  #   networks:
  #     - assist_network

  db:
    image: postgres:15-alpine
    container_name: ai_assist_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - assist_network

  # Новый сервис для веб-клиента
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: assist_web_client
    ports:
      - "3000:3000"
    environment:
      # URL должен указывать на внешний адрес сервера через nginx прокси
      - VITE_ASSISTANT_SERVER_URL=http://localhost:8000
      - VITE_USERNAME=admin
      - VITE_PASSWORD=password
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    # depends_on:
    #   - server
    networks:
      - assist_network

volumes:
  db_data:


networks:
  assist_network:
    driver: bridge
